const express = require('express');
const axios = require('axios');
const path = require('path');

const app = express();
const PORT = 3850;

app.use(express.json());
app.use(express.static(__dirname));

app.get('/api/readme', async (req, res) => {
  const { username } = req.query;
  if (!username) return res.status(400).json({ error: 'username required' });
  
  try {
    // Fetch user data from GitHub API
    const [userRes, reposRes] = await Promise.all([
      axios.get(`https://api.github.com/users/${username}`, { timeout: 8000 }),
      axios.get(`https://api.github.com/users/${username}/repos?sort=stars&per_page=100`, { timeout: 8000 })
    ]);
    
    const user = userRes.data;
    const repos = reposRes.data.filter(r => !r.fork);
    
    // Analyze repos
    const languages = {};
    const topRepos = repos.sort((a, b) => b.stargazers_count - a.stargazers_count).slice(0, 6);
    
    repos.forEach(r => {
      if (r.language) languages[r.language] = (languages[r.language] || 0) + 1;
    });
    
    const topLangs = Object.entries(languages)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([lang]) => lang);
    
    const totalStars = repos.reduce((s, r) => s + r.stargazers_count, 0);
    
    // Generate README
    const readme = generateReadme(user, topRepos, topLangs, totalStars);
    
    res.json({ readme, user: { name: user.name, login: user.login, bio: user.bio, avatar: user.avatar_url } });
  } catch(e) {
    if (e.response?.status === 404) return res.status(404).json({ error: 'GitHub user not found' });
    res.status(500).json({ error: e.message });
  }
});

function generateReadme(user, repos, langs, totalStars) {
  const name = user.name || user.login;
  const bio = user.bio || 'Building things';
  const location = user.location ? `📍 ${user.location}` : '';
  const company = user.company ? `🏢 ${user.company}` : '';
  const blog = user.blog ? `🌐 [Website](${user.blog})` : '';
  const followers = user.followers;
  
  // Language badges
  const langBadges = langs.map(l => {
    const slug = l.toLowerCase().replace(/ /g, '-').replace(/\+\+/g, 'pp').replace(/#/g, 'sharp');
    return `![${l}](https://img.shields.io/badge/${encodeURIComponent(l)}-informational?style=flat&logo=${slug}&logoColor=white&color=6366f1)`;
  }).join(' ');
  
  // Top repos section
  const repoCards = repos.slice(0, 4).map(r => 
    `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${user.login}&repo=${r.name}&theme=tokyonight)](https://github.com/${user.login}/${r.name})`
  ).join('\n');
  
  // Stats badges
  const statsUrl = `https://github-readme-stats.vercel.app/api?username=${user.login}&show_icons=true&theme=tokyonight&count_private=true`;
  const streakUrl = `https://github-readme-streak-stats.herokuapp.com/?user=${user.login}&theme=tokyonight`;
  const langsUrl = `https://github-readme-stats.vercel.app/api/top-langs/?username=${user.login}&layout=compact&theme=tokyonight`;
  
  const info = [location, company, blog].filter(Boolean).join(' · ');
  
  return `# Hi there, I'm ${name} 👋

> ${bio}

${info ? `**${info}**\n` : ''}
## 🚀 About Me

- 👀 **${followers}** followers · ⭐ **${totalStars}** stars earned
${user.public_repos > 0 ? `- 📂 **${user.public_repos}** public repositories` : ''}
${user.email ? `- 📧 ${user.email}` : ''}

## 🛠️ Languages & Tools

${langBadges || '*(Add your languages here)*'}

## 📊 GitHub Stats

<div align="center">

<img src="${statsUrl}" alt="GitHub Stats" height="165" />
<img src="${langsUrl}" alt="Top Languages" height="165" />

<img src="${streakUrl}" alt="GitHub Streak" />

</div>

## 📌 Featured Projects

${repoCards || '*(Add your projects here)*'}

---

<div align="center">

*Generated by [Yuki README Generator](https://tunnox-net.github.io/yuki-tools/) 🌸*

</div>
`;
}

app.listen(PORT, '0.0.0.0', () => console.log(`📝 README Generator on http://0.0.0.0:${PORT}`));
